apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        gilShin/awsomeNode: true
        gilShin/awsomenode2: true
        gilShin/cars-rest-api: true
        gilShin/gil-test: true
        gilShin/gil-test3: true
        gilShin/gil-test5: true
        gilShin/test-app: true
        gilShin/test-app2: true
        gilShin/test-jenkins-x-3: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        gilShin/awsomeNode: merge
        gilShin/awsomenode2: merge
        gilShin/cars-rest-api: merge
        gilShin/gil-test: merge
        gilShin/gil-test3: merge
        gilShin/gil-test5: merge
        gilShin/test-app: merge
        gilShin/test-app2: merge
        gilShin/test-jenkins-x-3: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - gilShin/test-jenkins-x-3
        - gilShin/awsomeNode
        - gilShin/awsomenode2
        - gilShin/cars-rest-api
        - gilShin/gil-test
        - gilShin/gil-test3
        - gilShin/gil-test5
        - gilShin/test-app
        - gilShin/test-app2
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - gilShin/test-jenkins-x-3
        - gilShin/awsomeNode
        - gilShin/awsomenode2
        - gilShin/cars-rest-api
        - gilShin/gil-test
        - gilShin/gil-test3
        - gilShin/gil-test5
        - gilShin/test-app
        - gilShin/test-app2
      target_url: http://dashboard-jx.192.168.99.100.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
