apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - gilShin/test-jenkins-x-3
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - gilShin/awsomeNode
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - gilShin/awsomenode2
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - gilShin/cars-rest-api
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - gilShin/gil-test
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - gilShin/test-app
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - gilShin/test-app2
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      gilShin/awsomeNode:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      gilShin/awsomenode2:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      gilShin/cars-rest-api:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      gilShin/gil-test:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      gilShin/test-app:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      gilShin/test-app2:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      gilShin/test-jenkins-x-3:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - gilShin/test-jenkins-x-3
      trusted_org: todo
    - repos:
      - gilShin/awsomeNode
      trusted_org: todo
    - repos:
      - gilShin/awsomenode2
      trusted_org: todo
    - repos:
      - gilShin/cars-rest-api
      trusted_org: todo
    - repos:
      - gilShin/gil-test
      trusted_org: todo
    - repos:
      - gilShin/test-app
      trusted_org: todo
    - repos:
      - gilShin/test-app2
      trusted_org: todo
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
