apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: gilShin
    provider: github
    repository: awsomeNode
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: gilshin-awsomenode
  namespace: jx
spec:
  httpCloneURL: https://github.com/gilShin/awsomeNode.git
  org: gilShin
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: awsomeNode
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/gilShin/awsomeNode
