apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: gilShin
    provider: github
    repository: cars-rest-api
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: gilshin-cars-rest-api
  namespace: jx
spec:
  httpCloneURL: https://github.com/gilShin/cars-rest-api.git
  org: gilShin
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: cars-rest-api
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/gilShin/cars-rest-api
